import "./globals.css";
import Headers from '@/components/layouts/Header'


export const metadata = {
  title: "Travel Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Headers/>
        {children}
      </body>
    </html>
  );
}
